//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QLCF.Module.dbQLCF
{

    public partial class CuaHang : XPObject
    {
        string fmacuahang;
        public string macuahang
        {
            get { return fmacuahang; }
            set { SetPropertyValue<string>(nameof(macuahang), ref fmacuahang, value); }
        }
        string ftencuahang;
        public string tencuahang
        {
            get { return ftencuahang; }
            set { SetPropertyValue<string>(nameof(tencuahang), ref ftencuahang, value); }
        }
        [Association(@"TaiKhoanReferencesCuaHang")]
        public XPCollection<TaiKhoan> TaiKhoans { get { return GetCollection<TaiKhoan>(nameof(TaiKhoans)); } }
        [Association(@"SanPhamReferencesCuaHang")]
        public XPCollection<SanPham> SanPhams { get { return GetCollection<SanPham>(nameof(SanPhams)); } }
    }

}
