//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QLCF.Module.dbQLCF
{

    public partial class DanhGiaSanPham : XPObject
    {
        string fmadanhgia;
        public string madanhgia
        {
            get { return fmadanhgia; }
            set { SetPropertyValue<string>(nameof(madanhgia), ref fmadanhgia, value); }
        }
        string fsosao;
        public string sosao
        {
            get { return fsosao; }
            set { SetPropertyValue<string>(nameof(sosao), ref fsosao, value); }
        }
        string fcomment;
        public string comment
        {
            get { return fcomment; }
            set { SetPropertyValue<string>(nameof(comment), ref fcomment, value); }
        }
        SanPham fsanpham;
        [Association(@"DanhGiaSanPhamReferencesSanPham")]
        public SanPham sanpham
        {
            get { return fsanpham; }
            set { SetPropertyValue<SanPham>(nameof(sanpham), ref fsanpham, value); }
        }
        TaiKhoan fmataikhoan;
        [Association(@"DanhGiaSanPhamReferencesTaiKhoan")]
        public TaiKhoan mataikhoan
        {
            get { return fmataikhoan; }
            set { SetPropertyValue<TaiKhoan>(nameof(mataikhoan), ref fmataikhoan, value); }
        }
    }

}
