//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QLCF.Module.dbQLCF
{

    public partial class DonHang : XPObject
    {
        string fmadonhang;
        public string madonhang
        {
            get { return fmadonhang; }
            set { SetPropertyValue<string>(nameof(madonhang), ref fmadonhang, value); }
        }
        string fngaydathang;
        public string ngaydathang
        {
            get { return fngaydathang; }
            set { SetPropertyValue<string>(nameof(ngaydathang), ref fngaydathang, value); }
        }
        string fdiachigiaohang;
        public string diachigiaohang
        {
            get { return fdiachigiaohang; }
            set { SetPropertyValue<string>(nameof(diachigiaohang), ref fdiachigiaohang, value); }
        }
        TrangThai ftrangthai;
        [Association(@"DonHangReferencesTrangThai")]
        public TrangThai trangthai
        {
            get { return ftrangthai; }
            set { SetPropertyValue<TrangThai>(nameof(trangthai), ref ftrangthai, value); }
        }
        TaiKhoan fmataikhoan;
        [Association(@"DonHangReferencesTaiKhoan")]
        public TaiKhoan mataikhoan
        {
            get { return fmataikhoan; }
            set { SetPropertyValue<TaiKhoan>(nameof(mataikhoan), ref fmataikhoan, value); }
        }
    }

}
