//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QLCF.Module.dbQLCF
{

    public partial class HoaDon : XPObject
    {
        string fmahoadon;
        public string mahoadon
        {
            get { return fmahoadon; }
            set { SetPropertyValue<string>(nameof(mahoadon), ref fmahoadon, value); }
        }
        string fngaytao;
        public string ngaytao
        {
            get { return fngaytao; }
            set { SetPropertyValue<string>(nameof(ngaytao), ref fngaytao, value); }
        }
        string fsanpham;
        public string sanpham
        {
            get { return fsanpham; }
            set { SetPropertyValue<string>(nameof(sanpham), ref fsanpham, value); }
        }
        string ftongbill;
        public string tongbill
        {
            get { return ftongbill; }
            set { SetPropertyValue<string>(nameof(tongbill), ref ftongbill, value); }
        }
        string fsoban;
        public string soban
        {
            get { return fsoban; }
            set { SetPropertyValue<string>(nameof(soban), ref fsoban, value); }
        }
        TaiKhoan fmataikhoan;
        [Association(@"HoaDonReferencesTaiKhoan")]
        public TaiKhoan mataikhoan
        {
            get { return fmataikhoan; }
            set { SetPropertyValue<TaiKhoan>(nameof(mataikhoan), ref fmataikhoan, value); }
        }
        [Association(@"ThanhToanReferencesHoaDon")]
        public XPCollection<ThanhToan> ThanhToans { get { return GetCollection<ThanhToan>(nameof(ThanhToans)); } }
    }

}
