//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QLCF.Module.dbQLCF
{

    public partial class Luong : XPObject
    {
        string fmatienluong;
        public string matienluong
        {
            get { return fmatienluong; }
            set { SetPropertyValue<string>(nameof(matienluong), ref fmatienluong, value); }
        }
        string ftienluong;
        public string tienluong
        {
            get { return ftienluong; }
            set { SetPropertyValue<string>(nameof(tienluong), ref ftienluong, value); }
        }
        TaiKhoan fmataikhoan;
        [Association(@"LuongReferencesTaiKhoan")]
        public TaiKhoan mataikhoan
        {
            get { return fmataikhoan; }
            set { SetPropertyValue<TaiKhoan>(nameof(mataikhoan), ref fmataikhoan, value); }
        }
        string fsogiolam;
        public string sogiolam
        {
            get { return fsogiolam; }
            set { SetPropertyValue<string>(nameof(sogiolam), ref fsogiolam, value); }
        }
        VaiTro fmavaitro;
        [Association(@"LuongReferencesVaiTro")]
        public VaiTro mavaitro
        {
            get { return fmavaitro; }
            set { SetPropertyValue<VaiTro>(nameof(mavaitro), ref fmavaitro, value); }
        }
    }

}
