//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QLCF.Module.dbQLCF
{

    public partial class NhanVien : XPObject
    {
        string fmanhanvien;
        public string manhanvien
        {
            get { return fmanhanvien; }
            set { SetPropertyValue<string>(nameof(manhanvien), ref fmanhanvien, value); }
        }
        string ftennhanvien;
        public string tennhanvien
        {
            get { return ftennhanvien; }
            set { SetPropertyValue<string>(nameof(tennhanvien), ref ftennhanvien, value); }
        }
        TaiKhoan ftaikhoan;
        [Association(@"NhanVienReferencesTaiKhoan")]
        public TaiKhoan taikhoan
        {
            get { return ftaikhoan; }
            set { SetPropertyValue<TaiKhoan>(nameof(taikhoan), ref ftaikhoan, value); }
        }
        VaiTro fmavaitro;
        [Association(@"NhanVienReferencesVaiTro")]
        public VaiTro mavaitro
        {
            get { return fmavaitro; }
            set { SetPropertyValue<VaiTro>(nameof(mavaitro), ref fmavaitro, value); }
        }
    }

}
