//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QLCF.Module.dbQLCF
{

    public partial class TaiKhoan : XPObject
    {
        string fmataikhoan;
        public string mataikhoan
        {
            get { return fmataikhoan; }
            set { SetPropertyValue<string>(nameof(mataikhoan), ref fmataikhoan, value); }
        }
        string ftentaikhoan;
        public string tentaikhoan
        {
            get { return ftentaikhoan; }
            set { SetPropertyValue<string>(nameof(tentaikhoan), ref ftentaikhoan, value); }
        }
        string fmatkhau;
        public string matkhau
        {
            get { return fmatkhau; }
            set { SetPropertyValue<string>(nameof(matkhau), ref fmatkhau, value); }
        }
        string fhoten;
        public string hoten
        {
            get { return fhoten; }
            set { SetPropertyValue<string>(nameof(hoten), ref fhoten, value); }
        }
        string femail;
        public string email
        {
            get { return femail; }
            set { SetPropertyValue<string>(nameof(email), ref femail, value); }
        }
        string fsdt;
        public string sdt
        {
            get { return fsdt; }
            set { SetPropertyValue<string>(nameof(sdt), ref fsdt, value); }
        }
        string fdiachi;
        public string diachi
        {
            get { return fdiachi; }
            set { SetPropertyValue<string>(nameof(diachi), ref fdiachi, value); }
        }
        string fgioitinh;
        public string gioitinh
        {
            get { return fgioitinh; }
            set { SetPropertyValue<string>(nameof(gioitinh), ref fgioitinh, value); }
        }
        CuaHang fmacuahang;
        [Association(@"TaiKhoanReferencesCuaHang")]
        public CuaHang macuahang
        {
            get { return fmacuahang; }
            set { SetPropertyValue<CuaHang>(nameof(macuahang), ref fmacuahang, value); }
        }
        [Association(@"DanhGiaSanPhamReferencesTaiKhoan")]
        public XPCollection<DanhGiaSanPham> DanhGiaSanPhams { get { return GetCollection<DanhGiaSanPham>(nameof(DanhGiaSanPhams)); } }
        [Association(@"LuongReferencesTaiKhoan")]
        public XPCollection<Luong> Luongs { get { return GetCollection<Luong>(nameof(Luongs)); } }
        [Association(@"ThanhToanReferencesTaiKhoan")]
        public XPCollection<ThanhToan> ThanhToans { get { return GetCollection<ThanhToan>(nameof(ThanhToans)); } }
        [Association(@"NhanVienReferencesTaiKhoan")]
        public XPCollection<NhanVien> NhanViens { get { return GetCollection<NhanVien>(nameof(NhanViens)); } }
        [Association(@"HoaDonReferencesTaiKhoan")]
        public XPCollection<HoaDon> HoaDons { get { return GetCollection<HoaDon>(nameof(HoaDons)); } }
        [Association(@"DonHangReferencesTaiKhoan")]
        public XPCollection<DonHang> DonHangs { get { return GetCollection<DonHang>(nameof(DonHangs)); } }
    }

}
