//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QLCF.Module.dbQLCF
{

    public partial class TrangThai : XPObject
    {
        string fmatrangthai;
        public string matrangthai
        {
            get { return fmatrangthai; }
            set { SetPropertyValue<string>(nameof(matrangthai), ref fmatrangthai, value); }
        }
        string ftentrangthai;
        public string tentrangthai
        {
            get { return ftentrangthai; }
            set { SetPropertyValue<string>(nameof(tentrangthai), ref ftentrangthai, value); }
        }
        [Association(@"DonHangReferencesTrangThai")]
        public XPCollection<DonHang> DonHangs { get { return GetCollection<DonHang>(nameof(DonHangs)); } }
    }

}
