//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QLCF.Module.dbQLCF
{

    public partial class VaiTro : XPObject
    {
        string fmavaitro;
        public string mavaitro
        {
            get { return fmavaitro; }
            set { SetPropertyValue<string>(nameof(mavaitro), ref fmavaitro, value); }
        }
        string ftenvaitro;
        public string tenvaitro
        {
            get { return ftenvaitro; }
            set { SetPropertyValue<string>(nameof(tenvaitro), ref ftenvaitro, value); }
        }
        [Association(@"LuongReferencesVaiTro")]
        public XPCollection<Luong> Luongs { get { return GetCollection<Luong>(nameof(Luongs)); } }
        [Association(@"NhanVienReferencesVaiTro")]
        public XPCollection<NhanVien> NhanViens { get { return GetCollection<NhanVien>(nameof(NhanViens)); } }
    }

}
